### PR TITLE
Discussion of ARCHIVE vs INNODB

### PR DESCRIPTION
**Pull request by michaelmcandrew**

### CODE REVIEW

**Comment by xurizaemon** [comment]
Related: [dev/core#663: Deprecate ARCHIVE format for CiviCRM Database Logging](https://lab.civicrm.org/dev/core/issues/663)

**Comment by MikeyMJCO** [comment]
In light of the core deprecation here I think this change is no longer relevant?

@michaelmcandrew can we close this one down?

**Comment by michaelmcandrew** [comment]
The current content is still inaccurate and does need improving - would be good to keep a note somewhere that the description of logging needs to be updated. Here seems good enough to (lazy) me, but if you have another suggestion, let me know.

**Comment by MikeyMJCO** [comment]
:+1: will leave it open here.

**Comment by mattwire** [comment]
As there will be lots of sites using ARCHIVE logging we still need to note here how to convert from ARCHIVE to InnoDB and note optimisations such as adding indexes (which the core implementation does not do).

**Comment by MegaphoneJon** [comment]
> As there will be lots of sites using ARCHIVE logging we still need to note here how to convert from ARCHIVE to InnoDB and note optimisations such as adding indexes (which the core implementation does not do).

I realize I'm getting a bit off-topic here - but does anyone know WHY the core implementation doesn't add indices?  Is it just a space/performance consideration?  It absolutely kills the speed of loading the "Change Log" tab of a contact, reverting changes, etc.

**Comment by mlutfy** [comment]
@MegaphoneJon Just curious: how many contacts do you have? On tables with 50-100k contacts, it loads pretty quickly for me (in innodb).

I don't think indexes are available for Archive? For innodb, considering it was not officially supported by core until recently, presumably it requires a bit more programming so that indexes are created. Are there disk space considerations? (mysql index files can be bulky on disk)

**Comment by jackrabbithanna** [comment]
My unasked for two cents.

**IMO Core should have indexes for the log tables**. 

We convert all our sites logging to innodb and add indexes, it's a must for performance with large data sets. Adding indexes can have a impact on disk / memory usage on the db server. But disk space is relatively cheap...and the memory problem .. We have a site that a Drupal entity type, that has about 60 million records, and it has like 8 compound fields (fields with more than one value column), so to query with lots of field conditions, it can get pretty hairy with alot of indexes .. in our case the indexes get loaded or involve the RAM, and we almost peg out a 128GB RAM hard metal box that only runs the db server (Percona db cluster master -> slave -> slave) and highly customized/configured.. but that's 60 million records, and joining to 8 or more field tables.

I can see how log tables could get that big, but you'd have to have a decent number of contacts / activities / contributions, with lots of recorded changes over time etc.. to reach a point where indexes using up HD or RAM are the problem. NOT having indexes / innodb on the other hand, is a problem, even with small 100K contact datasets.

100K Contacts, average  log table size 1 million maybe? maybe 10 million ? I'd totally do indexes for performance, and make the box strong enough disk space / RAM to handle it. I can tell you that without indexes, on sites with 100K + contacts, lots of activities and contributions and lots of updates that multiply the log table record count ..Even rebuilding smart group cache can have a real bad time without log indexes, real bad.

The speed problem without indexes, and the potential for db locks / slow queries that follow from that, is way worse a problem then storage space or memory, especially when you may be able to just throw resources at the problem. 

We had a case where the client had to have logging, really only 20K contacts, but millions of activities, 100s of smart groups. Civi is getting rapid fire activities created via api as users interact with the website, activities of certain types would cause users to be included smart groups .. and db locking was a huge problem until we added indexes. The admins would go to run a simple logging report, perhaps even for just one contact, and then the user's experience would kerplunk because of db locks .. after innodb and liberally applied indexes, 0 problems.

**Comment by JoeMurray** [comment]
So I'm not opposed to making use of indexes if they are available. But MySQL archive data engine does not support indexes. If people want to convert their logs to InnoDB then they are available. See https://dev.mysql.com/doc/refman/8.0/en/archive-storage-engine.html

**Comment by xurizaemon** [comment]
I think this docs change is an improvement over the current state.

@michaelmcandrew's phrasing is far kinder on ARGHCHIVE than I would be ...

Separately there's the issue of whether CiviCRM defaulting to ARCHIVE is a good idea, which I think is generally felt to be problematic and is being discussed in [dev/core#663: Deprecate ARCHIVE format for CiviCRM Database Logging](https://lab.civicrm.org/dev/core/issues/663).

I think while that's still in progress (?), we should merge this request, possibly now with mention of the fact that CiviCRM seems to be considering adopting InnoDB logging in some form as default behaviour - AFAICT it's what most CiviCRM shops do one they realise ARCHIVE is problematic, but I'm interested to hear from anyone who finds it works nicely for them!

**Comment by MikeyMJCO** [comment]
> 
> 
> I think this docs change is an improvement over the current state.
> 
> @michaelmcandrew's phrasing is far kinder on ARGHCHIVE than I would be ... it might give people the impression ARCHIVE is faster at writes and smaller for storage, and I believe the smaller storage but not sure about the rest (hence the initial question).
> 
> Separately there's the issue of whether CiviCRM defaulting to ARCHIVE is a good idea; my impression is ARCHIVE is generally felt to be problematic. Proposal, now concept approved:
> 
>     * [dev/core#663: Deprecate ARCHIVE format for CiviCRM Database Logging](https://lab.civicrm.org/dev/core/issues/663).
> 
> 
> I think while that's still in progress (?), we should merge this request, possibly now with mention of the fact that CiviCRM seems to be considering adopting InnoDB logging in some form as default behaviour - AFAICT it's what most CiviCRM shops do one they realise ARCHIVE is problematic, but I'm interested to hear from anyone who finds it works nicely for them!

So seeking clarity here:

Is the current default storage engine ARCHIVE or InnoDB?  If it's ARCHIVE then this is good to merge as @xurizaemon says. Otherwise we should update this further.

If anyone wants to take a crack at the "middle ground" solution where we have this text and clarify

**Comment by MikeyMJCO** [comment]
Sorry didn't mean to close.

**Comment by xurizaemon** [comment]
Oh, yesterday when I looked at dev/core#663 I saw the discussion and didn't see the recent commits merging it. So innodb log tables I guess will be default civicrm behavior for new installs/activators of DB logging as of the latest or next release? I believe existing sites/users of ARCHIVE will need to migrate manually.

There will still be lots of sites with existing ARCHIVE tables who need the docs of course. For clarity might be worth surfacing info about log format if that's not already in the status report.

**Comment by MikeyMJCO** [comment]
Ok so to commit here we'd need to update in light of the commit of [#663](https://lab.civicrm.org/dev/core/issues/663). So the docs are clear that from v5.(?) the default is/will be InnoDB whilst folding in the very good information on ARCHIVE and it's pros/cons that've been discussed here?

Anyone disagree with the above?

**Comment by jackrabbithanna** [comment]
We use this: https://github.com/eileenmcnaughton/nz.co.fuzion.innodbtriggers
to convert to innodb

**Comment by xurizaemon** [comment]
I expect CiviCRM will default to using InnoDB as of the next release (5.16), presuming that this behaviour change is consistent with a minor version release. We still kinda need ARCHIVE docs for those sites who haven't converted, but we probably want to document the process to get away from ARCHIVE as much as we want to offer support on how to live with it. Suggest something like:

---

## Database logging storage format.

CiviCRM sites which activated database logging before v5.16 defaulted to using ARCHIVE format storage. This format used less diskspace but often led to complications due to on the fly compression, hence its retirement as of CiviCRM 5.16.

### Converting from ARCHIVE to InnoDB

If you want to convert your DB log storage from ARCHIVE to InnoDB, you can do it with the API call `system.updatelogtables` with parameter `forceEngineMigration` set to `1`, eg:

```bash
cv api System.updatelogtables forceEngineMigration=1 
```

Note that executing this command will increase your disk storage and may take a long time to run.



## System requirements

* **MySQL database permissions** - Logging requires the usage of [MySQL Triggers](https://dev.mysql.com/doc/en/triggers.html), so your MySQL database user will need to have the correct permissions to use them. In most cases, you will need to grant the [Trigger Privilege](https://dev.mysql.com/doc/en/privileges-provided.html#priv_trigger). However, depending on your system or if you have enabled binary logging, you may need the [Super Privilege](https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_super).

**Comment by MikeyMJCO** [comment]
> 
> 
> I expect CiviCRM will default to using InnoDB as of the next release (5.16), presuming that this behaviour change is consistent with a minor version release. We still kinda need ARCHIVE docs for those sites who haven't converted, but we probably want to document the process to get away from ARCHIVE as much as we want to offer support on how to live with it. Suggest something like:
> ## Database logging storage format.
> 
> CiviCRM sites which activated database logging before v5.16 defaulted to using ARCHIVE format storage. The ARCHIVE format used less diskspace but often led to complications due to on the fly compression, hence its retirement as of CiviCRM 5.16.
> ### Converting from ARCHIVE to InnoDB
> 
> If you want to convert your DB log storage from ARCHIVE to InnoDB, you can do it with the API call `system.updatelogtables` with parameter `forceEngineMigration` set to `1`, eg:
> 
> ```shell
> cv api System.updatelogtables forceEngineMigration=1 
> ```
> 
> Note that executing this command is likely to increase storage requirements, and may take a long time to run, as existing logging data will be decompressed. This command should be safe to run on a site which already uses InnoDB storage.
> ## System requirements
> 
>     * **MySQL database permissions** - Logging requires the usage of [MySQL Triggers](https://dev.mysql.com/doc/en/triggers.html), so your MySQL database user will need to have the correct permissions to use them. In most cases, you will need to grant the [Trigger Privilege](https://dev.mysql.com/doc/en/privileges-provided.html#priv_trigger). However, depending on your system or if you have enabled binary logging, you may need the [Super Privilege](https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_super).

This looks good to me. It'd be great to give a *shout out* to @eileenmcnaughton's extension which is useful here as well!

**Comment by pfigel** [comment]
Whoops, looks like I forgot to reference this PR in #167 where I worked on the docs update for dev/core#663, so there's been a bit of duplicated effort, sorry about that! I'm happy to add anything that's missing in #167, or we can do it the other way 'round,  whatever the preference is.

**Comment by MikeyMJCO** [comment]
So #167 has been merged - is there anything left which warrants keeping this PR open?

**Comment by MikeyMJCO** [comment]
@michaelmcandrew @xurizaemon can you look this over during the sprint to see if we need to keep this or merge anything from this in in a new or refocussed PR.

**Comment by MikeyMJCO** [comment]
Sneaky nagging ping... @michaelmcandrew @xurizaemon

**Comment by michaelmcandrew** [comment]
Closing this in light of https://github.com/civicrm/civicrm-sysadmin-guide/pull/167

**Pull request closed without merging**
