### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by John-B**
This PR is a response to issues #27 and #39

### CODE REVIEW

**Comment by John-B** [comment]
"CiviCRM does not support serving specific pages via SSL under a different domain than your site's main domain, a feature which some hosts still offer as 'shared SSL.'"

Yes, best remove it. Almost no host retains this archaic system of offering SSL only on generic SSL domain different than the customer's domain.

As for:
"Automated installation and renewal sometimes causes problems not specific to CiviCRM, which is one reason why some users prefer paid certificates, manually installed."
I think it is ok to remove that. 
I have seen problems when (a) hosting companies try to auto-write a well-known/ directory and the codebase has been made unwritable for security reasons; and (b) because hosts sometimes auto-write to .haccess to permit external access to the .well-known directory if .htaccess otherswise blocks or rewrites it, and that can conflict with other rewrite rules in the .htaccess--which I have seen, when a host 'improved' their implementation of automated SSL installation. In addition cPanel's AutoSSL (an alternative to LetsEncrypt)  has recently be installing invalid certificates at a host I use. For these reasons, all problems I have encountered in the wild, I personally have problems with LetsEncrypt on a mission-critical site. On the basis that is my personal judgement, rather than a reflection of standard sysadmin practice, it probably does not belong in the CiviCRM documentation.

**Comment by mlutfy** [comment]
I understand your concerns, thanks for being flexible on this :)

Could you update your pull-request? You can add commits to your branch, and it will automatically update this pull request.

**Comment by John-B** [comment]
two sentences removed as agreed

**Comment by mlutfy** [comment]
Thanks again, looks good :)

**Pull request merged**
