### PR TITLE
Add BCMath as PHP requirement.

### PR DESCRIPTION
**Pull request by MikeyMJCO**

### CODE REVIEW

**Comment by JoeMurray** [comment]
My question is not about the documentation but the technical requirement. 

We've tried to avoid adding new requirements like PHP libraries, and have even been trying to reduce them. A) Do payment processor extensions really need this library? B) Shouldn't extensions manage their own requirements? 

If we agreed there was a need for many extensions to use something like BCMath and that most installations would use one of them then I would agree to adding it to general project requirements. @mattwire @eileenmcnaughton @totten 

If we go ahead with this, and it is merely because some payment processors use this library, then perhaps a slight weakening to a recommendation or something would be appropriate.

**Comment by MikeyMJCO** [comment]
I mean BCMath is a fairly standard PHP library - I'm not sure it's strictly required for anything and I don't disagree with weakening it to a requirement - there are other "requirements" in there which are only used for third party services or extensions.

E.g. PHP-SOAP.

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO yeah the whole section is too strong - even CURL is required less & less although we still need that as required IMHO

**Comment by mlutfy** [comment]
It's not just payment processors, there is a place in core using it.

Users have also reported it a few times:

- https://civicrm.stackexchange.com/questions/33204/sometimes-cant-save-content
- https://civicrm.stackexchange.com/questions/31932/error-call-to-undefined-function-bccomp-in-crm-financial-bao-paymentispayme/31965

It was first introduced in CiviCRM in 2016 (78c995161c9)

**Comment by eileenmcnaughton** [comment]
mcrypt shouldn't be in there now as it's not required & we would rather people didn't use it since we don't have a plan to get them off

**Comment by mattwire** [comment]
bcmath is required by a few bits in core (including phpseclib) and CRM/Financial/BAO/Payment.  As far as I'm aware it's not directly required by payment processors (stripe doesn't use it) but is required by core functionality that is required by payment processors :-)

**Comment by MikeyMJCO** [comment]
Moved Joe's initial comment to a new issue post (linked) worth a chat around further refactoring there.

**Comment by eileenmcnaughton** [comment]
OK - we should def update that to a required library & downgrade the messaging on the others (aside from curl)

**Comment by MikeyMJCO** [comment]
I'll clarify the docs change based on the other comment regarding BCMath being needed for core.

**Comment by MikeyMJCO** [comment]
Linked a new PR to refactor the page slightly.

**Pull request merged**
