### PR TITLE
update text re 2014 GSoC Bootstrap project

### PR DESCRIPTION
**Pull request by joemcl**

### CODE REVIEW

**Comment by mattwire** [comment]
> This entire section of information is out of date - we bundle Bootstrap.css in core.

@MikeyMJCO I'm pretty sure we don't... Shoreditch does and @totten and I had discussions about bundling with the Haystack theme extension.

**Comment by MikeyMJCO** [comment]
You're right we don't - we output Bootstrap 3 markup - couldn't remember which way we did it now.

**Comment by MikeyMJCO** [comment]
The section still needs reworking.

**Comment by MikeyMJCO** [comment]
Going to merge this - flagged section for future cleanup!

**Pull request merged**
