### PR TITLE
Update wordpress.md

### PR DESCRIPTION
**Pull request by netzih**
for cleaner URL's need to add base page in Please check that you the base page here: https://example.org/wp-admin/admin.php?page=CiviCRM&q=civicrm/admin/setting/uf&reset=1

### CODE REVIEW

**Comment by seamuslee001** [comment]
This looks the same as the fix here https://civicrm.stackexchange.com/questions/31232/wordpress-clean-urls-not-working-on-civi-5-14-0 @kcristiano can you confirm your happy with this

**Comment by netzih** [comment]
Yes. He responded to my issue. I'm just saying to update the readme

**Comment by kcristiano** [comment]
@seamuslee001 I am happy with it as it does need to be set, but perhaps we should add before the code snippet as it's a requirement.  Also we should link to the section that talks about base page (or create it if it does not exist).

**Comment by MikeyMJCO** [comment]
I agree with @kcristiano's feedback @netzih if you can make the changes @kcristiano suggests this change can be approved :-)

**Comment by MikeyMJCO** [comment]
I'm going to merge this - for further iterations/improvements please open a new PR.

**Pull request merged**
