### PR TITLE
Add tested cURL script for verifying Silent-post URL

### PR DESCRIPTION
**Pull request by ginkgomzd**
also add a warning against using a Silent-post URL that will trigger server redirects.

### CODE REVIEW

**Comment by John-B** [comment]
Sorry, I canont get this working. Some of the problems could be fixed by more explanation. However, there is still a problem. 

My data (-d) paramaters, contain the ID for a real subscription. By that I mean that the customer ID is a real contact_id and contribution_recur_id in civicrm_contribute, with a matching id in civicrm_contribution_recur.

My line  THE_URL="http://lawesome.org/civicrm/payment/ipn/1 is adusted to use my site's domain, and payment processor ID which matches and Authorize.net payment process set up in my CiviCRM site.

When running the script I get a response from authorize.net. However, Civi returns the error 'Could not find contributionRecur id'. 

Visiting the THE_URL path my browser returns error 
```

CRM_Core_Exception: Could not find an entry for x_subscription_id in /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Payment/AuthorizeNetIPN.php on line 57
--
Exception trace
# | Function | Location
0 | CRM_Core_Payment_AuthorizeNetIPN->retrieve('x_subscription_i…', 'String') | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Payment/AuthorizeNetIPN.php:57
1 | CRM_Core_Payment_AuthorizeNetIPN->main() | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Payment/AuthorizeNet.php:772
2 | CRM_Core_Payment_AuthorizeNet::handlePaymentNotification() | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Payment.php:1392
3 | CRM_Core_Payment::handlePaymentMethod('handlePaymentNot…', Array) | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Payment.php:1294
4 | CRM_Core_Payment::handleIPN() | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Invoke.php:275
5 | CRM_Core_Invoke::runItem(Array) | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Invoke.php:84
6 | CRM_Core_Invoke::_invoke(Array) | /buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Invoke.php:52
7 | CRM_Core_Invoke::invoke(Array) | /buildkit/build/dmaster/sites/all/modules/civicrm/drupal/civicrm.module:445
8 | civicrm_invoke('payment', 'ipn', '3') | /buildkit/build/dmaster/includes/menu.inc:527
9 | menu_execute_active_handler() | /buildkit/build/dmaster/index.php:21
10 | {main}
```

**Comment by mlutfy** [comment]
@John-B Isn't the subscription_id the ID from authorizenet?

I would support the clarification. (Although part of me also would prefer fixing this upstream, by having a clear IPN url proposed by CiviCRM, but short of having that, at least it's better documented)

**Comment by JoeMurray** [comment]
@eileen ^ re IPN

**Comment by seamuslee001** [comment]
@eileenmcnaughton ^

**Comment by eileenmcnaughton** [comment]
So I don't understand why this appears to be suggesting using the extern url - that is deprecated as far as I'm concerned - the issue here seems to be to determine whether with or without 'www' is the canonical url when coming up with 

http://www.mysite.com/civicrm/payment/ipn/1 
vs 
http://mysite.com/civicrm/payment/ipn/1 

ie. the equivalent of 'paste the above into your browser & if it changes then use the one it changes to?

**Comment by eileenmcnaughton** [comment]
Note that if you get an error complaining about lacking a valid id then it would seem you have the right url

**Comment by MikeyMJCO** [comment]
Hi All,

Trying to unstick/move on old docs issues - so what's stopping this issue progressing/what's needed to unstick it/should it be closed?

**Comment by eileenmcnaughton** [comment]
I think it's better in than out as it uses the right url! Although I think it's better without the ref to the old url

**Comment by eileenmcnaughton** [comment]
I removed that bit - so merging

**Pull request merged**
