### PR TITLE
Update switch-cms.md

### PR DESCRIPTION
**Pull request by kelizoliva**
Adding Drupal to Backdrop migration instructions.

### CODE REVIEW

**Comment by kelizoliva** [comment]
See comments on #176

**Comment by MegaphoneJon** [comment]
@kelizoliva There seems to be no changes in this PR?

**Comment by kelizoliva** [comment]
There sure weren't. Now there are.

**Comment by MikeyMJCO** [comment]
Thanks @kelizoliva :-)

However that page is getting out-of-control. I think I'll refactor that page into it's own section with a page for each migration workflow. At that point we'll ask you to split your changes out into a new markdown file if that's ok?

I'll hopefully have time to work on this later today or tomorrow.

**Comment by MikeyMJCO** [comment]
@kelizoliva I'm going to merge this now and refactor this section into separate pages today.

**Comment by MikeyMJCO** [comment]
Thanks!

**Pull request merged**
